Doccure.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Doccure.ViewModels;
using Doccure.Web.Services.Interfaces;

namespace Doccure.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;
        public HomeController(IHomeService homeService)
        {
            _homeService = homeService;
        }
        public IActionResult Index()
        {
            //feed index
            var data = _homeService.GetAdviserByMaxRate();
            return View();
        }
    }

}

Doccure.Web/ViewComponents/TopAdvisersViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Doccure.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Doccure.Web.ViewComponents
{
    public class TopAdvisersViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new List<AdviserViewModel>();
            return View(model);
        }
    }
}

Doccure.Web/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!-- Home Banner -->

<link type="image/x-icon" href="~/assets/img/favicon.png" rel="icon">
<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="~/assets/plugins/fontawesome/css/fontawesome.min.css">
<link rel="stylesheet" href="~/assets/plugins/fontawesome/css/all.min.css">
<link rel="stylesheet" href="~/assets/css/style.css">
<title>Doctor help</title>


<section class="section-search">
    <div class="container-fluid">
        <div class="banner-wrapper">
            <div class="banner-header text-center">
                <h1>Search Doctor, Make an Appointment</h1>
                <p>Discover the best doctors, nearest to you.</p>
            </div>

            <!-- Search -->
            <div class="search-box">
                <form action="#">
                    <div class="form-group search-location">
                        <input type="text" class="form-control" placeholder="Search Location">
                        <span class="form-text">Based on your Location</span>
                    </div>
                    <div class="form-group search-info">
                        <input type="text" class="form-control" placeholder="Search Doctors, Diseases, Etc.">
                        <span class="form-text">Ex : Ms.Smith or etc.</span>
                    </div>
                    <button type="submit" class="btn btn-primary search-btn"><i class="fas fa-search"></i> <span>Search</span></button>
                </form>
            </div>
            <!-- /Search -->

        </div>
    </div>
</section>
<!-- /Home Banner -->
<!-- Clinic and Specialities -->
<section class="section section-specialities">
    <div class="container-fluid">
        <div class="section-header text-center">
            <h2>Categories</h2>
            <p class="sub-title">Choose one of the Categories to get more information</p>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-9">
                <!-- Slider -->
                <div class="specialities-slider slider">

                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="~/assets/img/specialities/specialities-01.png" class="img-fluid" alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Urology</p>
                    </div>
                    <!-- /Slider Item -->
                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="~/assets/img/specialities/specialities-02.png" class="img-fluid" alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Neurology</p>
                    </div>
                    <!-- /Slider Item -->
                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="~/assets/img/specialities/specialities-03.png" class="img-fluid" alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Orthopedic</p>
                    </div>
                    <!-- /Slider Item -->
                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="~/assets/img/specialities/specialities-04.png" class="img-fluid" alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Cardiologist</p>
                    </div>
                    <!-- /Slider Item -->
                    <!-- Slider Item -->
                    <div class="speicality-item text-center">
                        <div class="speicality-img">
                            <img src="~/assets/img/specialities/specialities-05.png" class="img-fluid" alt="Speciality">
                            <span><i class="fa fa-circle" aria-hidden="true"></i></span>
                        </div>
                        <p>Dentist</p>
                    </div>
                    <!-- /Slider Item -->

                </div>
                <!-- /Slider -->

            </div>
        </div>
    </div>
</section>
<!-- Clinic and Specialities -->
@await Component.InvokeAsync("TopAdvisers")
<!-- /Main Wrapper -->
<!-- jQuery -->
<script src="~/assets/js/jquery.min.js"></script>

<!-- Bootstrap Core JS -->
<script src="~/assets/js/popper.min.js"></script>
<script src="~/assets/js/bootstrap.min.js"></script>
<!-- Slick JS -->
<script src="~/assets/js/slick.js"></script>
<!-- Custom JS -->
<script src="~/assets/js/script.js"></script>